routes/web.php
<?php

use App\Mail\MailtrapExample;
use Illuminate\Support\Facades\Mail;
Route::get('/send-mail', function () {
    Mail::to('prasenjit.aluni@gmail.com')->send(new MailtrapExample()); 
    return 'A message has been sent to Mailtrap!';
});

Route::get('/sendmail/{id}','Admin\EmployeeController@sendmail')->name('sendmail');






Route::get('imagickdev', 'HomeController@imagickdev')->name('imagickdev');

Route::redirect('/', 'index.php/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
	
	
	
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::resource('users', 'UsersController');

    // Employees
    Route::post('employees/addcertificate/{id}', 'EmployeeController@addcertificate')->name('employees.addcertificate');
	Route::get('employees/listing', 'EmployeeController@listing')->name('employees.listing');    
	Route::delete('employees/destroy', 'EmployeeController@massDestroy')->name('employees.massDestroy');
    Route::post('employees/parse-csv-import', 'EmployeeController@parseCsvImport')->name('employees.parseCsvImport');
    Route::post('employees/process-csv-import', 'EmployeeController@processCsvImport')->name('employees.processCsvImport');
    Route::resource('employees', 'EmployeeController');
    Route::get('employees/trainee/listing', 'EmployeeController@index')->name('employees.trainee.listing');    
	Route::get('employees/stategy/listing', 'EmployeeController@index')->name('employees.stategy.listing'); 
    
    // Trainees
    Route::post('trainees/addcertificate/{id}', 'TraineeController@addcertificate')->name('trainees.addcertificate');
	Route::get('trainees/listing', 'TraineeController@listing')->name('trainees.listing');    
	Route::delete('trainees/destroy', 'TraineeController@massDestroy')->name('trainees.massDestroy');
    Route::post('trainees/parse-csv-import', 'TraineeController@parseCsvImport')->name('trainees.parseCsvImport');
    Route::post('trainees/process-csv-import', 'TraineeController@processCsvImport')->name('trainees.processCsvImport');
    Route::resource('trainees', 'TraineeController');

	
	Route::get('internalemployees/showall', 'EmployeeinternalController@index')->name('internalemployees.showall');
	
    Route::get('internalemployees/search', 'EmployeeinternalController@empSearch')->name('internalemployees.empSearch');
    Route::post('internalemployees/search', 'EmployeeinternalController@empSearch')->name('internalemployees.empSearch');
    Route::delete('internalemployees/destroy', 'EmployeeinternalController@massDestroy')->name('internalemployees.massDestroy');
    Route::post('internalemployees/parse-csv-import', 'EmployeeinternalController@parseCsvImport')->name('internalemployees.parseCsvImport');
    Route::post('internalemployees/process-csv-import', 'EmployeeinternalController@processCsvImport')->name('internalemployees.processCsvImport');
    Route::resource('internalemployees', 'EmployeeinternalController');
	
	/*****
	Route::post('employees/parse-csv-import', 'EmployeeController@parseCsvImport')->name('employees.parseCsvImport');
    Route::post('employees/process-csv-import', 'EmployeeController@processCsvImport')->name('employees.processCsvImport');
    	
	
	/******/
	
	
	Route::get('employees/certificateapprove/{empid}', 'EmployeeController@certificateapprove')->name('employees.certificateapprove');
	Route::get('employees/certificatereview/{empid}', 'EmployeeController@certificatereview')->name('employees.certificatereview');
	Route::get('employees/certificatepdf/{empid}', 'EmployeeController@certificatepdf')->name('employees.certificatepdf');
	

	
	
    // Certificates
    Route::delete('certificates/destroy', 'CertificateController@massDestroy')->name('certificates.massDestroy');
    Route::post('certificates/media', 'CertificateController@storeMedia')->name('certificates.storeMedia');
    Route::post('certificates/ckmedia', 'CertificateController@storeCKEditorImages')->name('certificates.storeCKEditorImages');
    Route::resource('certificates', 'CertificateController');
	
    // Departments
    Route::delete('departments/destroy', 'DepartmentController@massDestroy')->name('departments.massDestroy');
    Route::resource('departments', 'DepartmentController');	
	
    // Members
	Route::get('members/all', 'EmployeeController@allmember')->name('members.all');
    Route::delete('members/destroy', 'MemberController@massDestroy')->name('members.massDestroy');
    Route::post('members/parse-csv-import', 'MemberController@parseCsvImport')->name('members.parseCsvImport');
    Route::post('members/process-csv-import', 'MemberController@processCsvImport')->name('members.processCsvImport');
    Route::resource('members', 'MemberController');	
	
    // Internalmembers
    Route::delete('internalmembers/destroy', 'InternalmemberController@massDestroy')->name('internalmembers.massDestroy');
    Route::post('internalmembers/parse-csv-import', 'InternalmemberController@parseCsvImport')->name('internalmembers.parseCsvImport');
    Route::post('internalmembers/process-csv-import', 'InternalmemberController@processCsvImport')->name('internalmembers.processCsvImport');
    Route::resource('internalmembers', 'InternalmemberController');	
	
	Route::get('/democode','EmployeeController@democode');
	Route::resource('crud','CrudsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

app/Internalmember.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class Internalmember extends Model
{
    use SoftDeletes;

    public $table = 'internalmembers';

    protected $dates = [
        'certificate_approve_date',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    const EMPLOYEE_TYPE_SELECT = [
        '1' => 'Internal Employee',
        '2' => 'External Employee',
    ];

    const CERTIFICATE_APPROVAL_STATUS_SELECT = [
        '1' => 'Pending',
        '2' => 'Approved',
        '3' => 'Canceled',
    ];

    const EMP_CATEGORY_SELECT = [
        '1' => 'Mr.',
        '2' => 'Mrs.',
        '3' => 'Ms.',
        '4' => 'Dr.',
        '5' => 'Eng.',
		'6' => 'تناتيتسن',
        '7' => 'Others',
    ];

    protected $fillable = [
		'emp_type',
		'emp_id',
        'emp_category',
        'first_name',
        'last_name',
		'emailid',		
        'institution_name',    
		'contact_no',
		'department'
		/*'emp_category',
        'first_name',
        'last_name',
        'institution_name',
        'emailid',
        'contact_no',
        'certificate_approval_status',
        'certificate_approve_by',
        'certificate_approve_date',
        'certificate_qrcode',
        'default_certificate',
        'created_by',
        'employee_type',
        'created_at',
        'updated_at',
        'deleted_at',*/
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function getCertificateApproveDateAttribute($value)
    {
        return $value ? Carbon::parse($value)->format(config('panel.date_format')) : null;
    }

    public function setCertificateApproveDateAttribute($value)
    {
        $this->attributes['certificate_approve_date'] = $value ? Carbon::createFromFormat(config('panel.date_format'), $value)->format('Y-m-d') : null;
    }
}

app/Http/Controllers/Admin/InternalmemberController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyInternalmemberRequest;
use App\Http\Requests\StoreInternalmemberRequest;
use App\Http\Requests\UpdateInternalmemberRequest;
use App\Internalmember;
use App\Department;
use Gate;
use Auth;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class InternalmemberController extends Controller
{
    use CsvImportTrait;

    public function index()
    {
        abort_if(Gate::denies('internalmember_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
	if(Auth::user()->department == NULL){
		$internalmembers = Internalmember::get();
//		dd($internalmembers);
	}
	else{
		$internalmembers = Internalmember::where('department', Auth::user()->department)->get();
		//$internalmembers = Internalmember::where('emp_type', Auth::user()->user_type)->where('department', Auth::user()->department)->get();			
	}

	//dd(Auth::user()->user_type);
        //dd(Auth::user()->user_type,$internalmembers);
        return view('admin.internalmembers.index', compact('internalmembers'));
    }

    public function create()
    {
        abort_if(Gate::denies('internalmember_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		$department = Department::get();
        return view('admin.internalmembers.create',compact('department'));
    }

    public function store(StoreInternalmemberRequest $request)
    {
	$internalmember = Internalmember::create($request->all());
	//$res = Internalmember::get();

	//dd($res->toArray(),$request->all());
        return redirect()->route('admin.internalmembers.index');
    }

    public function edit(Internalmember $internalmember)
    {
        abort_if(Gate::denies('internalmember_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.internalmembers.edit', compact('internalmember'));
    }

    public function update(UpdateInternalmemberRequest $request, Internalmember $internalmember)
    {
        $internalmember->update($request->all());

        return redirect()->route('admin.internalmembers.index');
    }

    public function show(Internalmember $internalmember)
    {
        abort_if(Gate::denies('internalmember_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.internalmembers.show', compact('internalmember'));
    }

    public function destroy(Internalmember $internalmember)
    {
        abort_if(Gate::denies('internalmember_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $internalmember->delete();

        return back();
    }

    public function massDestroy(MassDestroyInternalmemberRequest $request)
    {
        Internalmember::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/strategy/internalmembers/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.internalmember.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.internalmembers.store") }}" enctype="multipart/form-data">
            @csrf
			<div class="form-group">
				<label class="required" for="emp_id">{{ trans('cruds.internalmember.fields.emp_id') }}</label>
				<input class="form-control {{ $errors->has('emp_id') ? 'is-invalid' : '' }}" type="text" name="emp_id" id="emp_id" value="{{ old('emp_id', '') }}" required>
				@if($errors->has('emp_id'))
					<div class="invalid-feedback">
						{{ $errors->first('emp_id') }}
					</div>
				@endif
				<span class="help-block d-none">{{ trans('cruds.internalmember.fields.emp_id_helper') }}</span>
			</div>
            
			<div class="form-group">
                <label class="required">{{ trans('cruds.internalmember.fields.emp_category') }}</label>
                <select class="form-control {{ $errors->has('emp_category') ? 'is-invalid' : '' }}" name="emp_category" id="emp_category" required>
                    <option value disabled {{ old('emp_category', null) === null ? 'selected' : '' }}>{{ trans('global.pleaseSelect') }}</option>
                    @foreach(App\Internalmember::EMP_CATEGORY_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('emp_category', '1') === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('emp_category'))
                    <div class="invalid-feedback">
                        {{ $errors->first('emp_category') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.internalmember.fields.emp_category_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="first_name">{{ trans('cruds.internalmember.fields.first_name') }}</label>
                <input class="form-control {{ $errors->has('first_name') ? 'is-invalid' : '' }}" type="text" name="first_name" id="first_name" value="{{ old('first_name', '') }}" required>
                @if($errors->has('first_name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('first_name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.internalmember.fields.first_name_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="last_name">{{ trans('cruds.internalmember.fields.last_name') }}</label>
                <input class="form-control {{ $errors->has('last_name') ? 'is-invalid' : '' }}" type="text" name="last_name" id="last_name" value="{{ old('last_name', '') }}">
                @if($errors->has('last_name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('last_name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.internalmember.fields.last_name_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="institution_name">{{ trans('cruds.internalmember.fields.institution_name') }}</label>
                <input class="form-control {{ $errors->has('institution_name') ? 'is-invalid' : '' }}" type="text" name="institution_name" id="institution_name" value="{{ old('institution_name', '') }}">
                @if($errors->has('institution_name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('institution_name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.internalmember.fields.institution_name_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="emailid">{{ trans('cruds.internalmember.fields.emailid') }}</label>
                <input class="form-control {{ $errors->has('emailid') ? 'is-invalid' : '' }}" type="email" name="emailid" id="emailid" value="{{ old('emailid') }}">
                @if($errors->has('emailid'))
                    <div class="invalid-feedback">
                        {{ $errors->first('emailid') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.internalmember.fields.emailid_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="contact_no">{{ trans('cruds.internalmember.fields.contact_no') }}</label>
                <input class="form-control {{ $errors->has('contact_no') ? 'is-invalid' : '' }}" type="text" name="contact_no" id="contact_no" value="{{ old('contact_no', '') }}">
                @if($errors->has('contact_no'))
                    <div class="invalid-feedback">
                        {{ $errors->first('contact_no') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.internalmember.fields.contact_no_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="department">{{ trans('cruds.internalmember.fields.department') }}</label>
                
				<input  class="form-control {{ $errors->has('department') ? 'is-invalid' : '' }}" type="text" name="department" id="department" value="{{ old('department', Auth::user()->department) }}" required @if(!in_array(Auth::user()->roles[0]->title,array('Admin'))){{ 'readonly' }}@endif>				
                @if($errors->has('department'))
                    <div class="invalid-feedback">
                        {{ $errors->first('department') }}
                    </div>
                @endif
                <span class="help-block d-none">{{ trans('cruds.internalmember.fields.department_helper') }}</span>
            </div>
						
			
			<div class="d-none">
            <div class="form-group">
                <label>{{ trans('cruds.internalmember.fields.certificate_approval_status') }}</label>
                <select class="form-control {{ $errors->has('certificate_approval_status') ? 'is-invalid' : '' }}" name="certificate_approval_status" id="certificate_approval_status">
                    <option value disabled {{ old('certificate_approval_status', null) === null ? 'selected' : '' }}>{{ trans('global.pleaseSelect') }}</option>
                    @foreach(App\Internalmember::CERTIFICATE_APPROVAL_STATUS_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('certificate_approval_status', '1') === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('certificate_approval_status'))
                    <div class="invalid-feedback">
                        {{ $errors->first('certificate_approval_status') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.internalmember.fields.certificate_approval_status_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="certificate_approve_by">{{ trans('cruds.internalmember.fields.certificate_approve_by') }}</label>
                <input class="form-control {{ $errors->has('certificate_approve_by') ? 'is-invalid' : '' }}" type="number" name="certificate_approve_by" id="certificate_approve_by" value="{{ old('certificate_approve_by', '0') }}" step="1">
                @if($errors->has('certificate_approve_by'))
                    <div class="invalid-feedback">
                        {{ $errors->first('certificate_approve_by') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.internalmember.fields.certificate_approve_by_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="certificate_approve_date">{{ trans('cruds.internalmember.fields.certificate_approve_date') }}</label>
                <input class="form-control date {{ $errors->has('certificate_approve_date') ? 'is-invalid' : '' }}" type="text" name="certificate_approve_date" id="certificate_approve_date" value="{{ old('certificate_approve_date') }}">
                @if($errors->has('certificate_approve_date'))
                    <div class="invalid-feedback">
                        {{ $errors->first('certificate_approve_date') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.internalmember.fields.certificate_approve_date_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="certificate_qrcode">{{ trans('cruds.internalmember.fields.certificate_qrcode') }}</label>
                <textarea class="form-control {{ $errors->has('certificate_qrcode') ? 'is-invalid' : '' }}" name="certificate_qrcode" id="certificate_qrcode">{{ old('certificate_qrcode') }}</textarea>
                @if($errors->has('certificate_qrcode'))
                    <div class="invalid-feedback">
                        {{ $errors->first('certificate_qrcode') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.internalmember.fields.certificate_qrcode_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="default_certificate">{{ trans('cruds.internalmember.fields.default_certificate') }}</label>
                <input class="form-control {{ $errors->has('default_certificate') ? 'is-invalid' : '' }}" type="number" name="default_certificate" id="default_certificate" value="{{ old('default_certificate', '1') }}" step="1">
                @if($errors->has('default_certificate'))
                    <div class="invalid-feedback">
                        {{ $errors->first('default_certificate') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.internalmember.fields.default_certificate_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="created_by">{{ trans('cruds.internalmember.fields.created_by') }}</label>
                <input class="form-control {{ $errors->has('created_by') ? 'is-invalid' : '' }}" type="number" name="created_by" id="created_by" value="{{ old('created_by', '1') }}" step="1">
                @if($errors->has('created_by'))
                    <div class="invalid-feedback">
                        {{ $errors->first('created_by') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.internalmember.fields.created_by_helper') }}</span>
            </div>
			</div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/strategy/internalmembers/index.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('cruds.internalmember.title_singular') }} {{ trans('global.list') }}
		
		
@can('internalmember_create')
			<button class="btn btn-warning float-right" data-toggle="modal" data-target="#csvImportModal">
                {{ trans('global.app_csvImport') }}
            </button>
            
            <a class="btn btn-success float-right mr-2" href="{{ route('admin.internalmembers.create') }}">
                {{ trans('global.add') }} <?php /*{{ trans('cruds.internalmember.title_singular') }}*/?>
            </a>
            @include('csvImport.modal', ['model' => 'Internalmember', 'route' => 'admin.internalmembers.parseCsvImport'])
			<?php /*@include('csvImport.modal', ['model' => 'Member', 'route' => 'admin.employees.parseCsvImport'])	*/?>

@endcan		
		
		
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Internalmember">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.internalmember.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.internalmember.fields.emp_id') }}
                        </th>
                        <th>
                            {{ trans('cruds.internalmember.fields.emp_category') }}
                        </th>
                        <th>
                            {{ trans('cruds.internalmember.fields.first_name') }}
                        </th>
                        <th>
                            {{ trans('cruds.internalmember.fields.last_name') }}
                        </th>
                        <th>
                            {{ trans('cruds.internalmember.fields.institution_name') }}
                        </th>
                        <th>
                            {{ trans('cruds.internalmember.fields.emailid') }}
                        </th>
                        <th>
                            {{ trans('cruds.internalmember.fields.contact_no') }}
                        </th>
                        <th>
                            {{ trans('cruds.internalmember.fields.department') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($internalmembers as $key => $internalmember)
                        <tr data-entry-id="{{ $internalmember->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $internalmember->id ?? '' }}
                            </td>
                            <td>
                                {{ $internalmember->emp_id ?? '' }}
                            </td>
                            <td>
                                {{ App\Internalmember::EMP_CATEGORY_SELECT[$internalmember->emp_category] ?? '' }}
                            </td>
                            <td>
                                {{ $internalmember->first_name ?? '' }}
                            </td>
                            <td>
                                {{ $internalmember->last_name ?? '' }}
                            </td>
                            <td>
                                {{ $internalmember->institution_name ?? '' }}
                            </td>
                            <td>
                                {{ $internalmember->emailid ?? '' }}
                            </td>
                            <td>
                                {{ $internalmember->contact_no ?? '' }}
                            </td>
                            <td>
                                {{ $internalmember->department ?? '' }}
                            </td>
                            <td>
                                @can('internalmember_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.internalmembers.show', $internalmember->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('internalmember_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.internalmembers.edit', $internalmember->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('internalmember_delete')
                                    <form action="{{ route('admin.internalmembers.destroy', $internalmember->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('internalmember_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.internalmembers.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Internalmember:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection