routes/web.php
<?php

use App\Mail\MailtrapExample;
use Illuminate\Support\Facades\Mail;
Route::get('/send-mail', function () {
    Mail::to('prasenjit.aluni@gmail.com')->send(new MailtrapExample()); 
    return 'A message has been sent to Mailtrap!';
});

Route::get('/sendmail/{id}','Admin\EmployeeController@sendmail')->name('sendmail');






Route::get('imagickdev', 'HomeController@imagickdev')->name('imagickdev');

Route::redirect('/', 'index.php/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
	
	
	
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::resource('users', 'UsersController');

    // Employees
    Route::post('employees/addcertificate/{id}', 'EmployeeController@addcertificate')->name('employees.addcertificate');
	Route::get('employees/listing', 'EmployeeController@listing')->name('employees.listing');    
	Route::delete('employees/destroy', 'EmployeeController@massDestroy')->name('employees.massDestroy');
    Route::post('employees/parse-csv-import', 'EmployeeController@parseCsvImport')->name('employees.parseCsvImport');
    Route::post('employees/process-csv-import', 'EmployeeController@processCsvImport')->name('employees.processCsvImport');
    Route::resource('employees', 'EmployeeController');
    Route::get('employees/trainee/listing', 'EmployeeController@index')->name('employees.trainee.listing');    
	Route::get('employees/stategy/listing', 'EmployeeController@index')->name('employees.stategy.listing'); 
    
    // Trainees
    Route::post('trainees/addcertificate/{id}', 'TraineeController@addcertificate')->name('trainees.addcertificate');
	Route::get('trainees/listing', 'TraineeController@listing')->name('trainees.listing');    
	Route::delete('trainees/destroy', 'TraineeController@massDestroy')->name('trainees.massDestroy');
    Route::post('trainees/parse-csv-import', 'TraineeController@parseCsvImport')->name('trainees.parseCsvImport');
    Route::post('trainees/process-csv-import', 'TraineeController@processCsvImport')->name('trainees.processCsvImport');
    Route::resource('trainees', 'TraineeController');

	
	Route::get('internalemployees/showall', 'EmployeeinternalController@index')->name('internalemployees.showall');
	
    Route::get('internalemployees/search', 'EmployeeinternalController@empSearch')->name('internalemployees.empSearch');
    Route::post('internalemployees/search', 'EmployeeinternalController@empSearch')->name('internalemployees.empSearch');
    Route::delete('internalemployees/destroy', 'EmployeeinternalController@massDestroy')->name('internalemployees.massDestroy');
    Route::post('internalemployees/parse-csv-import', 'EmployeeinternalController@parseCsvImport')->name('internalemployees.parseCsvImport');
    Route::post('internalemployees/process-csv-import', 'EmployeeinternalController@processCsvImport')->name('internalemployees.processCsvImport');
    Route::resource('internalemployees', 'EmployeeinternalController');
	
	/*****
	Route::post('employees/parse-csv-import', 'EmployeeController@parseCsvImport')->name('employees.parseCsvImport');
    Route::post('employees/process-csv-import', 'EmployeeController@processCsvImport')->name('employees.processCsvImport');
    	
	
	/******/
	
	
	Route::get('employees/certificateapprove/{empid}', 'EmployeeController@certificateapprove')->name('employees.certificateapprove');
	Route::get('employees/certificatereview/{empid}', 'EmployeeController@certificatereview')->name('employees.certificatereview');
	Route::get('employees/certificatepdf/{empid}', 'EmployeeController@certificatepdf')->name('employees.certificatepdf');
	

	
	
    // Certificates
    Route::delete('certificates/destroy', 'CertificateController@massDestroy')->name('certificates.massDestroy');
    Route::post('certificates/media', 'CertificateController@storeMedia')->name('certificates.storeMedia');
    Route::post('certificates/ckmedia', 'CertificateController@storeCKEditorImages')->name('certificates.storeCKEditorImages');
    Route::resource('certificates', 'CertificateController');
	
    // Departments
    Route::delete('departments/destroy', 'DepartmentController@massDestroy')->name('departments.massDestroy');
    Route::resource('departments', 'DepartmentController');	
	
    // Members
	Route::get('members/all', 'EmployeeController@allmember')->name('members.all');
    Route::delete('members/destroy', 'MemberController@massDestroy')->name('members.massDestroy');
    Route::post('members/parse-csv-import', 'MemberController@parseCsvImport')->name('members.parseCsvImport');
    Route::post('members/process-csv-import', 'MemberController@processCsvImport')->name('members.processCsvImport');
    Route::resource('members', 'MemberController');	
	
    // Internalmembers
    Route::delete('internalmembers/destroy', 'InternalmemberController@massDestroy')->name('internalmembers.massDestroy');
    Route::post('internalmembers/parse-csv-import', 'InternalmemberController@parseCsvImport')->name('internalmembers.parseCsvImport');
    Route::post('internalmembers/process-csv-import', 'InternalmemberController@processCsvImport')->name('internalmembers.processCsvImport');
    Route::resource('internalmembers', 'InternalmemberController');	
	
	Route::get('/democode','EmployeeController@democode');
	Route::resource('crud','CrudsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

app/Http/Controllers/Admin/EmployeeController.php
<?php
namespace App\Http\Controllers\Admin;
use App\Certificate;
use App\Employee;
use App\User;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyEmployeeRequest;
use App\Http\Requests\StoreEmployeeRequest;
use App\Http\Requests\UpdateEmployeeRequest;
use App\Internalmember;
use App\Department;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use PDF;
use Auth;
use DB;
use URL;
use Route;
//use Mail;
use Libern\QRCodeReader\QRCodeReader;
use Zxing\QrReader;
use App\Mail\MailtrapExample;
use Illuminate\Support\Facades\Mail;


class EmployeeController extends Controller
{
    use CsvImportTrait;

	function sendmail(Request $request) {
		
		$res = Employee::where('id',$request->id)->get()->toArray();
		if(isset($res[0]['pdf_generated']) && $res[0]['pdf_generated'] == 0){
			$this->certificatepdf($request->id);
		}
		//$this->certificatepdf($request->id);
		
		
		//dd(public_path('/'));
		$data = [
			"to" => "prasenjit.aluni@gmail.com",
			"attachments" => [
				[
					"path" => 'pdf/certificate-'.$request->id.'.pdf',
					"as" => "certificate.pdf",
					"mime" => "application/pdf",
				]
			],
		];		
		Mail::to($data['to'])->send(new MailtrapExample($data));
		Employee::where('id',$request->id)->update(array('mail_sent'=>1));
		return redirect()->route('admin.employees.index')->with('success','Mail sent successfully');;;;
		return 'Mail sent successfully!';
		
		
		
		$data = array();
		$pathToFile = 'pdf\certificate-20.pdf';
		Mail::to('prasenjit.aluni@gmail.com')->send(new MailtrapExample(), $data, function ($message) {
			$pathToFile = asset('pdf/certificate-20.pdf');
			$message->attach('images/sitelogo.jpg', ['as' => 'Logo', 'mine'=>'application/jpeg']);
		});
		//Mail::to('prasenjit.aluni@gmail.com')->send(new MailtrapExample(), $data, function ($message) {$message->attach('pdf/certificate-20.pdf');}); 
		
	}

	
	public function democode(){}
	
	public function allmember(Request $request){
		abort_if(Gate::denies('employee_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		$certificate = array();
		$res = Certificate::select('id','certificate_title','department')->get()->toArray();
		
		foreach($res as $val){
			$certificate[$val['id']]['id'] = $val['id'];
			$certificate[$val['id']]['certificate_title'] 	= $val['certificate_title'];
			$certificate[$val['id']]['department'] 			= $val['department'];
		}
		//dd($certificate);
        $employees = Employee::get();
		
		if(Auth::user()->roles[0]->title == 'Admin'){
			$employees = Employee::get();
		}
		elseif(Auth::user()->roles[0]->title == 'Officer'){
			$employees = Employee::where('created_by',Auth::user()->id)->get();
		}
		else{			
			$employees = Employee::where('department',Auth::user()->department)->get();
		}
		
		
        $users = User::all();
		$usersname = array();
		foreach($users as $val){
			$usersname[$val->id] = $val->name;
		}
		$type = 3;
		$mass_actiontxt = '';
		if(Auth::user()->roles[0]->title == 'Manager'){
			$mass_actiontxt = 'Reviewed';
		}
		elseif(Auth::user()->roles[0]->title == 'HOD'){
			$mass_actiontxt = 'Approved';
		}
        return view('admin.employees.external.index', compact('employees','certificate','usersname','type','mass_actiontxt'));
	}
	
	
    public function index(Request $request){
		//dd(attachFromStorage());
		//dd(Route::current()->getName(),URL::current());

		
        abort_if(Gate::denies('employee_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		$certapprovestatus = 1;
		
		if(in_array(Auth::user()->roles[0]->title,array('TraineeOfficer','StrategyOfficer'))){
			$certapprovestatus = 2;
			$uar['certificate_approval_status'] = 2;
			//Employee::whereIn('department',['TraningDept','StrategyDept'])->update($uar);			
		}		
		/*
		$type = 'external';
		if($request->type == 'internal'){
			$type = 'internal';
		}
		*/
				$certificate = array();
		$res = Certificate::select('id','certificate_title','department')->get()->toArray();
		
		foreach($res as $val){
			$certificate[$val['id']]['id'] = $val['id'];
			$certificate[$val['id']]['certificate_title'] 	= $val['certificate_title'];
			$certificate[$val['id']]['department'] 			= $val['department'];
		}
		//dd($certificate);
		
		$employees = array();
		$whr = array();
        $whereIn = array();
		$whr['employee_type'] = 2;
		if(Auth::user()->roles[0]->title == 'Admin' || Auth::user()->roles[0]->title == 'Principal'){
			if(Route::current()->getName() == 'admin.employees.stategy.listing'){
				$whr['emp_type']	= 2;				
				$employees = Employee::where($whr)->get();				
			}			
			elseif(Route::current()->getName() == 'admin.employees.trainee.listing'){
				$whr['emp_type']	= 3;				
				$employees = Employee::where($whr)->get();
			}			
			else{
				$whr['emp_type']	= 1;
				//$employees = Employee::where($whr)->whereNotIn('department',array('StrategyDept','TraningDept'))->get();
				$employees = Employee::where($whr)->get();
			}
			
		}
		elseif(Auth::user()->roles[0]->title == 'Officer'){
			$whr['emp_type'] 		= Auth::user()->user_type;
			$whr['created_by']		= Auth::user()->id;
			//$whr['certificate_approval_status']	= 1;
			$employees = Employee::where($whr)->get();
			//$employees = Employee::where('employee_type',2)->where('created_by',Auth::user()->id)->get();
		}
		elseif(Auth::user()->roles[0]->title == 'Manager'){
			$whr['emp_type'] 	= Auth::user()->user_type;
			$whr['department']	= Auth::user()->department;
			$employees = Employee::where($whr)->get();
			//$employees = Employee::where($whr)->whereIn('certificate_approval_status',[1,4])->get();
		}
		elseif(Auth::user()->roles[0]->title == 'HOD'){
			$whr['emp_type'] 		= Auth::user()->user_type;
			$whr['employee_type'] 	= 2;
			$whr['department']		= Auth::user()->department;
			//$whr['certificate_approval_status']	= 4;
			//$whr = array();
			$employees = Employee::where($whr)->get();
		}
		
        $users = User::all();
		$usersname = array();
		foreach($users as $val){
			$usersname[$val->id] = $val->name;
		}
		$type = 2;
		$mass_actiontxt = '';
		if(Auth::user()->roles[0]->title == 'Manager'){
			$mass_actiontxt = 'Reviewed';
		}
		elseif(Auth::user()->roles[0]->title == 'HOD'){
			$mass_actiontxt = 'Approved';
		}
		elseif(in_array(Auth::user()->roles[0]->title,array('TraineeOfficer','StrategyOfficer'))){
			$mass_actiontxt = 'Approved';
		}
		//dd($employees);
		
        return view('admin.employees.external.index', compact('employees','certificate','usersname','type','mass_actiontxt'));

    }

    public function create(){
        abort_if(Gate::denies('employee_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		$certapprovestatus = 1;
		
		if(in_array(Auth::user()->roles[0]->title,array('TraineeOfficer','StrategyOfficer'))){
			$certapprovestatus = 2;
			$uar['certificate_approval_status'] = 2;
			//Certificate::where('department','StrategyDept')->update($uar);			
		}		
		$department = Department::get();
		
		$certificate = array();
		//dd(Auth::user()->roles[0]->title);
		//dd(Auth::user()->department);
		if(Auth::user()->roles[0]->title == 'Admin' || Auth::user()->roles[0]->title == 'Principal'){
			$res = Certificate::select('id','certificate_title','department','serial_prefix','serial_no')->get()->toArray();
		}
		else{
			$res = Certificate::select('id','certificate_title','department','serial_prefix','serial_no')->where('type',Auth::user()->user_type)->where('department',Auth::user()->department)->get()->toArray();
		}
		
		
		foreach($res as $val){
			$certificate[$val['id']]['id'] 					= $val['id'];
			$certificate[$val['id']]['certificate_title'] 	= $val['certificate_title'];
			$certificate[$val['id']]['department'] 			= $val['department'];
			$certificate[$val['id']]['serial_prefix'] 		= $val['serial_prefix'];
			$certificate[$val['id']]['serial_no'] 			= $val['serial_no']+1;
			$serial_no 										= $val['serial_no']+1;			
		}
		if(count($certificate) == 0){
			echo "<h3>Please create certificate.</h3>";
			exit;
		}
		
		$type = 2;

		//dd($serial_no);
		//serial_prefix,serial_no
		
        return view('admin.employees.external.create', compact('certificate','type','certapprovestatus','department','serial_no'));
    }

    public function store(StoreEmployeeRequest $request)
    {
		/*if(in_array(Auth::user()->roles[0]->title,array('TraineeOfficer','StrategyOfficer'))){
			$request->certificate_approval_status = 2;
		}
		if(Auth::user()->roles[0]->title == 'HOD'){
			$request->certificate_approval_status = 4;
		}*/
		//$request->emp_type = Auth::user()->user_type;
		
		if(!empty($request->serial_no)){
			Certificate::where('id',$request->default_certificate)->update(array('serial_no'=>$request->serial_no));
		}
		
		//dd($request->default_certificate, $request->serial_no);
		
		
		
		$employee = Employee::create($request->all());
		//dd(Auth::user()->roles[0]->title,$request->all());
		
		if($request->employee_type == 1){
			return redirect()->route('admin.members.index');
		}
		else{
			return redirect()->route('admin.employees.index');
		}		        
    }

    public function edit(Employee $employee)
    {
        abort_if(Gate::denies('employee_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		$certificate = array();
		$res = Certificate::select('id','certificate_title','department')->get()->toArray();
		
		foreach($res as $val){
			$certificate[$val['id']]['id'] = $val['id'];
			$certificate[$val['id']]['certificate_title'] = $val['certificate_title'];
			$certificate[$val['id']]['department'] 			= $val['department'];
		}
		$department = Department::get();
        return view('admin.employees.external.edit', compact('employee','certificate','department'));
    }

    public function update(UpdateEmployeeRequest $request, Employee $employee)
    {
        $employee->update($request->all());
		if($request->employee_type == 1){
			return redirect()->route('admin.members.index');
		}
		else{
			return redirect()->route('admin.employees.index');

resources/views/admin/employees/external/index.blade.php
<?php //dd($employees)?>
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
		@if(Auth::user()->roles[0]->title == 'TraineeOfficer')
			{{ trans('global.ctraining') }}
		@elseif(Auth::user()->roles[0]->title == 'StrategyOfficer')
			{{ trans('global.sctraining') }}
		@else
			@if($type == 2)
				{{ trans('cruds.employee.title_singular') }} 
			@else
				{{ trans('cruds.employee.internal_certificate') }} 
			@endif	
			{{ trans('global.list') }}
		@endif			
		
		

	
@can('employee_create') 
	@if(Auth::user()->user_type != 0)@endif	
		@if($type == 2)
			<a class="btn btn-warning float-right" href="{{ route('admin.employees.create') }}">
				{{ trans('global.add') }} <?php /*{{ trans('cruds.employee.title_singular') }}*/?>
			</a>
		@elseif($type == 3)
			<a class="btn btn-success float-right mr-2" href="{{ route('admin.members.create') }}">
				{{ trans('global.add') }} <?php /* {{ trans('cruds.employee.internal_certificate') }}*/?>
			</a> 
			<a class="btn btn-warning float-right mr-2" href="{{ route('admin.employees.create') }}">
				{{ trans('global.add') }} <?php /*{{ trans('cruds.employee.title_singular') }}*/?>
			</a>
		@elseif($type == 4)
			<a class="btn btn-success float-right" href="{{ route('admin.members.create') }}">
				{{ trans('global.add') }} <?php /*{{ trans('global.internal_employee') }}*/?>
			</a>
			<button class="btn btn-warning float-right" data-toggle="modal" data-target="#csvImportModal">
				{{ trans('global.app_csvImport') }}
			</button>	
			@include('csvImport.modal', ['model' => 'Member', 'route' => 'admin.employees.parseCsvImport'])					
		@else
			<a class="btn btn-success float-right" href="{{ route('admin.internalemployees.empSearch') }}">
				{{ trans('global.add') }} <?php /*{{ trans('cruds.employee.internal_certificate') }}*/ ?>
			</a>
			<?php /*<button class="btn btn-warning" data-toggle="modal" data-target="#csvImportModal">
				{{ trans('global.app_csvImport') }}
			</button>
			@include('csvImport.modal', ['model' => 'Employee', 'route' => 'admin.employees.parseCsvImport'])*/ ?>
								
		@endif
				            									
@endcan	
	
    </div>	
	
<?php if(session('success')){ ?>
    <div class="col-12">
<div class="alert alert-success fade in alert-dismissible show" style="margin-top:18px;">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true" style="font-size:20px">×</span>
  </button>  {{session('success')}}
 </div>
</div>
<?php } ?>
    <div class="card-body">
        <div class="table-responsive">
			<?php //echo Auth::user()->name;?>
            <table class=" table table-bordered table-striped table-hover datatable datatable-Employee">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.employee.fields.id') }}
                        </th>
						<?php /*
						<th>
                            {{ trans('global.ctype') }}
                        </th>*/ ?>
						<th>{{ trans('cruds.employee.fields.department') }}</th>
                        
						@if(in_array($type,array(1,3)))
                        <th>							
                            {{ trans('cruds.employee.fields.emp_id') }}
                        </th>
						@endif
                        <th>							
                            {{ trans('cruds.employee.fields.emp_category') }}
                        </th>
                        <th>
                            {{ trans('cruds.employee.fields.first_name') }}
                        </th>
                        <th>
                            {{ trans('cruds.employee.fields.last_name') }}
                        </th>
						<th>
                            {{ trans('cruds.employee.fields.emailid') }}
                        </th>
						@if(!in_array($type,array(1,3)))
						<th>
                            {{ trans('cruds.employee.fields.institution_name') }}
                        </th>
						@endif
						@if($type != 4)						
						<th>
                            {{ trans('cruds.employee.fields.default_certificate') }}
                        </th>
                        <th>
                            {{ trans('cruds.employee.fields.certificate_approval_status') }}
                        </th>
						<th>{{ trans('global.created_by') }}</th>
						@if(!in_array(Auth::user()->roles[0]->title,array('TraineeOfficer','StrategyOfficer')))
                        <th>{{ trans('global.reviewed_by') }}</th>
                        <th>{{ trans('global.approved_by') }}</th>	
						@endif
						@endif
						<th>&nbsp;</th>                        
                    </tr>
                </thead>
                <tbody>
                    @foreach($employees as $key => $employee)
						
                        <tr data-entry-id="{{ $employee->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $employee->id ?? '' }}
                            </td>
							
							<?php /*
							<td>
								@if($employee->emp_type == 1)
									General
								@elseif($employee->emp_type == 2)
									Strategy
								@elseif($employee->emp_type == 3)
									Trainee
								@endif
                            </td>                            
							*/ ?>
							<td>
                                {{ $employee->department ?? '' }}
                            </td>
							
							@if(in_array($type,array(1,3)))
                            <td>
                                {{ $employee->emp_id ?? '' }}
                            </td>
							@endif
                            <td>
								{{ App\Employee::EMP_CATEGORY_SELECT[$employee->emp_category] ?? '' }} 
							</td>
							<td>
								{{ $employee->first_name ?? '' }} 
							</td>
							<td>
								{{ $employee->last_name ?? '' }}
                            </td>
                            <td>
								{{ $employee->emailid ?? 'N/A' }}
                            </td>
							@if(!in_array($type,array(1,3)))
                            <td>
                                {{ $employee->institution_name ?? '' }}
                            </td>
							@endif
							@if($type != 4)	
							<td>
								@if(isset($certificate[$employee->default_certificate]['certificate_title']))
									<a href="/admin/certificates/{{$employee->default_certificate}}/" target="_blank">
										{{ $certificate[$employee->default_certificate]['certificate_title'] }}
									</a>
								@endif								
                            </td>

                            
                            <td>
								<?php //echo '<pre>';print_r(Auth::user()->roles[0]->title);echo '<pre>';?>
								
								{{ App\Employee::CERTIFICATE_APPROVAL_STATUS_SELECT[$employee->certificate_approval_status] ?? '' }}
																										
								@if(Auth::user()->roles[0]->title == 'HOD' || Auth::user()->roles[0]->title == 'Principal')
									@if(App\Employee::CERTIFICATE_APPROVAL_STATUS_SELECT[$employee->certificate_approval_status] == 'Reviewed')
									@endif
									@if($employee->certificate_approval_status != 2)
										<a class="btn btn-xs btn-info" href="{{ route('admin.employees.certificateapprove', $employee->id) }}">
											Approve
										</a>
									@endif
								@elseif(Auth::user()->roles[0]->title == 'Manager')
									@if(App\Employee::CERTIFICATE_APPROVAL_STATUS_SELECT[$employee->certificate_approval_status] == 'Pending')
									<a class="btn btn-xs btn-info" href="{{ route('admin.employees.certificatereview', $employee->id) }}">
										Review
									</a>	
									@endif
								@endif
								
								
								@if(App\Employee::CERTIFICATE_APPROVAL_STATUS_SELECT[$employee->certificate_approval_status] == 'Approved')
									<a class="btn btn-xs btn-info d-none" href="{{ route('admin.employees.certificatepdf', $employee->id) }}" target="_blank">
										Certificate PDF
									</a>
								@endif																								
                            </td>
                            <td>
								@if(isset($usersname[$employee->created_by]))
									{{ $usersname[$employee->created_by] }}
								@endif
                            </td> 
							@if(!in_array(Auth::user()->roles[0]->title,array('TraineeOfficer','StrategyOfficer')))
                            <td>
								@if(isset($usersname[$employee->reviewed_by]))
									{{ $usersname[$employee->reviewed_by] }}
								@endif
                            </td>                            
                            <td>
								@if(isset($usersname[$employee->certificate_approve_by]))
									{{ $usersname[$employee->certificate_approve_by] }}
								@endif
                            </td>                            							
							@endif
                            @endif
                            <td>
								@if($type != 4)	
									@if(isset($certificate[$employee->default_certificate]['certificate_title']))
										@if($employee->pdf_generated == 1)											
											<a class="fa fa-file-pdf-o" href="{{ asset('pdf/certificate-'.$employee->id.'.pdf') }}" target="_blank">
											</a>
										@endif
										<a class="btn btn-xs btn-success" href="{{ route('admin.employees.certificatepdf', $employee->id) }}" target="_blank">
											{{trans('global.certificate')}}
										</a>										
										
										@if($employee->certificate_approval_status == 2)
											@if($employee->mail_sent == 0)
												<a href="{{ route('sendmail',$employee->id) }}" target="_blank" class="btn btn-xs btn-info" >Send Mail</a>
											@else
												<a href="{{ route('sendmail',$employee->id) }}" target="_blank" class="btn btn-xs btn-warning" >Mail Sent</a>
											@endif
										@endif										
									@endif	
								@endif
                                @can('employee_show')
                                    <a class="btn btn-xs btn-primary d-none" href="{{ route('admin.employees.show', $employee->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

								
								@can('employee_edit')
									<a class="btn btn-xs btn-primary" href="{{ route('admin.employees.edit', $employee->id) }}">
										{{ trans('global.edit') }}
									</a>
								@endcan
								@if($employee->certificate_approval_status == 1)
									@can('employee_delete')
										<form action="{{ route('admin.employees.destroy', $employee->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
											<input type="hidden" name="_method" value="DELETE">
											<input type="hidden" name="_token" value="{{ csrf_token() }}">
											<input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
										</form>
									@endcan
								@endif
                            </td>
														
                        </tr>
                    @endforeach
                </tbody>
            </table>
        
		
		</div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('employee_delete')
  let deleteButtonTrans = '{{ $mass_actiontxt}}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.employees.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE', "_token": "{{ csrf_token() }}", }})
          .done(function () { location.reload() })
      }
    }
  }
  @if(in_array(Auth::user()->roles[0]->title,array('HOD','Manager')))
  dtButtons.push(deleteButton);
  @endif
  
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Employee:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection