routes/web.php
<?php

use App\Mail\MailtrapExample;
use Illuminate\Support\Facades\Mail;
Route::get('/send-mail', function () {
    Mail::to('prasenjit.aluni@gmail.com')->send(new MailtrapExample()); 
    return 'A message has been sent to Mailtrap!';
});

Route::get('/sendmail/{id}','Admin\EmployeeController@sendmail')->name('sendmail');






Route::get('imagickdev', 'HomeController@imagickdev')->name('imagickdev');

Route::redirect('/', 'index.php/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
	
	
	
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::resource('users', 'UsersController');

    // Employees
    Route::post('employees/addcertificate/{id}', 'EmployeeController@addcertificate')->name('employees.addcertificate');
	Route::get('employees/listing', 'EmployeeController@listing')->name('employees.listing');    
	Route::delete('employees/destroy', 'EmployeeController@massDestroy')->name('employees.massDestroy');
    Route::post('employees/parse-csv-import', 'EmployeeController@parseCsvImport')->name('employees.parseCsvImport');
    Route::post('employees/process-csv-import', 'EmployeeController@processCsvImport')->name('employees.processCsvImport');
    Route::resource('employees', 'EmployeeController');
    Route::get('employees/trainee/listing', 'EmployeeController@index')->name('employees.trainee.listing');    
	Route::get('employees/stategy/listing', 'EmployeeController@index')->name('employees.stategy.listing'); 
    
    // Trainees
    Route::post('trainees/addcertificate/{id}', 'TraineeController@addcertificate')->name('trainees.addcertificate');
	Route::get('trainees/listing', 'TraineeController@listing')->name('trainees.listing');    
	Route::delete('trainees/destroy', 'TraineeController@massDestroy')->name('trainees.massDestroy');
    Route::post('trainees/parse-csv-import', 'TraineeController@parseCsvImport')->name('trainees.parseCsvImport');
    Route::post('trainees/process-csv-import', 'TraineeController@processCsvImport')->name('trainees.processCsvImport');
    Route::resource('trainees', 'TraineeController');

	
	Route::get('internalemployees/showall', 'EmployeeinternalController@index')->name('internalemployees.showall');
	
    Route::get('internalemployees/search', 'EmployeeinternalController@empSearch')->name('internalemployees.empSearch');
    Route::post('internalemployees/search', 'EmployeeinternalController@empSearch')->name('internalemployees.empSearch');
    Route::delete('internalemployees/destroy', 'EmployeeinternalController@massDestroy')->name('internalemployees.massDestroy');
    Route::post('internalemployees/parse-csv-import', 'EmployeeinternalController@parseCsvImport')->name('internalemployees.parseCsvImport');
    Route::post('internalemployees/process-csv-import', 'EmployeeinternalController@processCsvImport')->name('internalemployees.processCsvImport');
    Route::resource('internalemployees', 'EmployeeinternalController');
	
	/*****
	Route::post('employees/parse-csv-import', 'EmployeeController@parseCsvImport')->name('employees.parseCsvImport');
    Route::post('employees/process-csv-import', 'EmployeeController@processCsvImport')->name('employees.processCsvImport');
    	
	
	/******/
	
	
	Route::get('employees/certificateapprove/{empid}', 'EmployeeController@certificateapprove')->name('employees.certificateapprove');
	Route::get('employees/certificatereview/{empid}', 'EmployeeController@certificatereview')->name('employees.certificatereview');
	Route::get('employees/certificatepdf/{empid}', 'EmployeeController@certificatepdf')->name('employees.certificatepdf');
	

	
	
    // Certificates
    Route::delete('certificates/destroy', 'CertificateController@massDestroy')->name('certificates.massDestroy');
    Route::post('certificates/media', 'CertificateController@storeMedia')->name('certificates.storeMedia');
    Route::post('certificates/ckmedia', 'CertificateController@storeCKEditorImages')->name('certificates.storeCKEditorImages');
    Route::resource('certificates', 'CertificateController');
	
    // Departments
    Route::delete('departments/destroy', 'DepartmentController@massDestroy')->name('departments.massDestroy');
    Route::resource('departments', 'DepartmentController');	
	
    // Members
	Route::get('members/all', 'EmployeeController@allmember')->name('members.all');
    Route::delete('members/destroy', 'MemberController@massDestroy')->name('members.massDestroy');
    Route::post('members/parse-csv-import', 'MemberController@parseCsvImport')->name('members.parseCsvImport');
    Route::post('members/process-csv-import', 'MemberController@processCsvImport')->name('members.processCsvImport');
    Route::resource('members', 'MemberController');	
	
    // Internalmembers
    Route::delete('internalmembers/destroy', 'InternalmemberController@massDestroy')->name('internalmembers.massDestroy');
    Route::post('internalmembers/parse-csv-import', 'InternalmemberController@parseCsvImport')->name('internalmembers.parseCsvImport');
    Route::post('internalmembers/process-csv-import', 'InternalmemberController@processCsvImport')->name('internalmembers.processCsvImport');
    Route::resource('internalmembers', 'InternalmemberController');	
	
	Route::get('/democode','EmployeeController@democode');
	Route::resource('crud','CrudsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

app/Certificate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;
use \DateTimeInterface;

class Certificate extends Model implements HasMedia
{
    use SoftDeletes, HasMediaTrait;

    public $table = 'certificates';

    protected $appends = [
        'certificate_logo',
        'certificate_signature',
		'stamp'
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];


    const TEMPLATE_RADIO = [
        '1' => 'Template 1',
        '2' => 'Template 2',
    ];	
	
    protected $fillable = [
        'template',
		'certificate_issue_by_post',
		'certificate_issue_by_officername',
		'certificate_issue_msg',
		'certificate_title',
        'certificate_subtitle',
        'certificate_details',
		'department',
        'created_by',
        'empid',
		'serial_prefix',
		'serial_no',		
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->width(50)->height(50);
    }

    public function getCertificateLogoAttribute()
    {
        $file = $this->getMedia('certificate_logo')->last();

        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
        }

        return $file;
    }
	
    public function getCertificateSignatureAttribute()
    {
        $file = $this->getMedia('certificate_signature')->last();

        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
        }

        return $file;
    }
	
    public function getStampAttribute()
    {
        $file = $this->getMedia('stamp')->last();

        if ($file) {
            $file->url       = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
        }

        return $file;
    }	
}

app/Http/Controllers/Admin/CertificateController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Certificate;
use App\Department;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyCertificateRequest;
use App\Http\Requests\StoreCertificateRequest;
use App\Http\Requests\UpdateCertificateRequest;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\Models\Media;
use Symfony\Component\HttpFoundation\Response;
use Auth;
//

class CertificateController extends Controller
{
    use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('certificate_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        if(Auth::user()->roles[0]->title == 'Admin' || Auth::user()->roles[0]->title == 'Principal'){
			$certificates = Certificate::get();
		}
		else{
			$certificates = Certificate::where('department',Auth::user()->department)->get();
		}
		

        return view('admin.certificates.index', compact('certificates'));
    }

    public function create()
    {
        abort_if(Gate::denies('certificate_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		$department = Department::get()->toArray();
        return view('admin.certificates.create',compact('department'));
    }

    public function store(StoreCertificateRequest $request)
    {
        $certificate = Certificate::create($request->all());

        if ($request->input('certificate_logo', false)) {
            $certificate->addMedia(storage_path('tmp/uploads/' . $request->input('certificate_logo')))->toMediaCollection('certificate_logo');
        }

        if ($request->input('certificate_signature', false)) {
            $certificate->addMedia(storage_path('tmp/uploads/' . $request->input('certificate_signature')))->toMediaCollection('certificate_signature');
        }		

        if ($request->input('stamp', false)) {
            $certificate->addMedia(storage_path('tmp/uploads/' . $request->input('stamp')))->toMediaCollection('stamp');
        }
		
        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $certificate->id]);
        }

        return redirect()->route('admin.certificates.index');
    }

    public function edit(Certificate $certificate)
    {
        abort_if(Gate::denies('certificate_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		//dd($certificate);
		$department = Department::get()->toArray();
        return view('admin.certificates.edit', compact('certificate','department'));
    }

    public function update(UpdateCertificateRequest $request, Certificate $certificate)
    {
		$certificate->update($request->all());

        if ($request->input('certificate_logo', false)) {
            if (!$certificate->certificate_logo || $request->input('certificate_logo') !== $certificate->certificate_logo->file_name) {
                $certificate->addMedia(storage_path('tmp/uploads/' . $request->input('certificate_logo')))->toMediaCollection('certificate_logo');
            }
        } elseif ($certificate->certificate_logo) {
            $certificate->certificate_logo->delete();
        }

        if ($request->input('certificate_signature', false)) {
            if (!$certificate->certificate_signature || $request->input('certificate_signature') !== $certificate->certificate_signature->file_name) {
                $certificate->addMedia(storage_path('tmp/uploads/' . $request->input('certificate_signature')))->toMediaCollection('certificate_signature');
            }
        } elseif ($certificate->certificate_signature) {
            $certificate->certificate_signature->delete();
        }

        if ($request->input('stamp', false)) {
            if (!$certificate->stamp || $request->input('stamp') !== $certificate->stamp->file_name) {
                $certificate->addMedia(storage_path('tmp/uploads/' . $request->input('stamp')))->toMediaCollection('stamp');
            }
        } elseif ($certificate->stamp) {
            $certificate->stamp->delete();
        }
		
        return redirect()->route('admin.certificates.index');
    }

    public function show(Certificate $certificate)
    {
        abort_if(Gate::denies('certificate_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.certificates.show', compact('certificate'));
    }

    public function destroy(Certificate $certificate)
    {
        abort_if(Gate::denies('certificate_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $certificate->delete();

        return back();
    }

    public function massDestroy(MassDestroyCertificateRequest $request)
    {
        Certificate::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('certificate_create') && Gate::denies('certificate_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new Certificate();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/certificates/index.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('cruds.certificate.title_singular') }} {{ trans('global.list') }}
		
@can('certificate_create')

            <a class="btn btn-success float-right" href="{{ route('admin.certificates.create') }}">
                {{ trans('global.add') }} <?php /*{{ trans('cruds.certificate.title_singular') }}*/ ?>
            </a>
@endcan		
		
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Certificate">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.certificate.fields.id') }}
                        </th>
                        <?php /*<th>
                            {{ trans('cruds.certificate.fields.template') }}
                        </th>
						
                        <th>
                            {{ trans('global.ctype') }}
                        </th>
						*/ ?>
                        <th>
                            {{ trans('cruds.user.fields.department') }}
                        </th>
                        <th>
                            {{ trans('cruds.certificate.fields.certificate_title') }}
                        </th>
                        <th>
                            {{ trans('cruds.certificate.fields.certificate_subtitle') }}
                        </th>
                        <?php /*<th>
                            {{ trans('cruds.certificate.fields.certificate_logo') }}
                        </th>*/?>                        
                        <th>
                            {{ trans('global.action') }}
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($certificates as $key => $certificate)
                        <tr data-entry-id="{{ $certificate->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $certificate->id ?? '' }}
                            </td>
                            <?php /*<td>								
                                <?php /*{{ App\Certificate::TEMPLATE_RADIO[$certificate->template] ?? '' }}* ?>
								<img src="{{asset('/images/template'.$certificate->template.'.jpg')}}" width="100" style="margin:10px; " />
                            </td>
							
                            <td>
								@if($certificate->type == 1)
									General
								@elseif($certificate->type == 2)
									Strategy
								@elseif($certificate->type == 3)
									Trainee
								@endif
                            </td>
							*/ ?>
                            <td>
                                {{ $certificate->department ?? '' }}
                            </td>
                            <td>
                                {{ $certificate->certificate_title ?? '' }}
                            </td>
                            <td>
                                {{ $certificate->certificate_subtitle ?? '' }}
                            </td>
                            <?php /*
							<td>
								
                                @if($certificate->certificate_logo)
									@php($certificateImgURL = $certificate->certificate_logo->getUrl('thumb'))
									@php($certificateLargeImgURL = $certificate->certificate_logo->getUrl())
									<a href="{{ $certificateLargeImgURL }}" target="_blank">
                                        <img src="{{ $certificateImgURL }}" width="50px" height="50px">
                                    </a>
                                @endif
                            </td>*/?>
                            <td>
                                @can('certificate_show')
                                    <a class="btn btn-xs btn-primary d-none" href="{{ route('admin.certificates.show', $certificate->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('certificate_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.certificates.edit', $certificate->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('certificate_delete')
                                    <form action="{{ route('admin.certificates.destroy', $certificate->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block; display:none;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('certificate_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.certificates.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Certificate:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/certificates/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.certificate.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.certificates.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.certificate.fields.id') }}
                        </th>
                        <td>
                            {{ $certificate->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.certificate.fields.certificate_title') }}
                        </th>
                        <td>
                            {{ $certificate->certificate_title }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.certificate.fields.certificate_subtitle') }}
                        </th>
                        <td>
                            {{ $certificate->certificate_subtitle }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.certificate.fields.certificate_details') }}
                        </th>
                        <td>
                            {!! $certificate->certificate_details !!}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.certificate.fields.certificate_logo') }}
                        </th>
                        <td>
                            @if($certificate->certificate_logo)
                                <a href="{{ $certificate->certificate_logo->getUrl() }}" target="_blank">
                                    <img src="{{ $certificate->certificate_logo->getUrl('thumb') }}" width="50px" height="50px">
                                </a>
                            @endif
                        </td>
                    </tr>                    
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.certificates.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection